### ISSUE TITLE
Author blog post on the architecture

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/application-shell#12]
- Summarise server-side setup w/Express
- Summarise how we're tackling routing
- Summarise how we tackled async loading resources

**Comment by gauntface** [comment]
Where do you want this documented? Docs in the project or somewhere else?

**Comment by addyosmani** [comment]
Docs in the project. We can either do this in the readme or in a `/docs/` directory. Imo, this is something that would be super-helpful to folks first looking at the project. Could eventually be fleshed out into something on Web Fundamentals.

**Comment by addyosmani** [comment]
Server-side architecture diagram is now up [here](https://docs.google.com/presentation/d/1S0uIj5DaKATwYz_24b2-fD0Jz7HQoq4qDBmT42itYhc/edit#slide=id.p). @gauntface is going to update my first stab at this once he's had a chance to go through the code again tomorrow.

**Comment by addyosmani** [comment]
Posts are staged and will go out later today.
