### ISSUE TITLE
Cross-browser testing 🔧

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/application-shell#18]
@gauntface I've seen a little flakiness when testing the latest build locally and was wondering if you could find it in your :heart to do a little cross-browser testing on your end in case it's just me.
- [x] Verify a fresh clone + install works in Chrome stable + canary (first view, repeat view, navigating to different pages)
- [x] Verify this works in Firefox stable (without any SW flags on)
- [x] Test if this works in Firefox nightly with SW on
- [ ] Test in Safari and if possible Edge

**Comment by gauntface** [comment]
Tested all of the above apart from Edge (The VM seemed to not want to unzip on OS X and on Ubuntu my Virtualbox is out of date and I can't update it - Yay).

**Comment by addyosmani** [comment]
Thanks a lot for taking the time to test. I'll get it verified up on Edge and we can close this issue up.

**Comment by addyosmani** [comment]
All good here now.
