### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/application-shell#22]
# TODOs

List of things we've discussed that need doing on app-shell
- [ ] Use MDL.
- [ ] Move over voice memos to use this.
- [ ] . . . .

**Comment by addyosmani** [comment]
Let's talk about how we could use MDL for this. We'll likely need a custom build with:
- Layout/navigation component
- Cards
- Do we need buttons/FAB at all?

In terms of where we then house the source for this, do we want to place all of our MDL source for build in `third_party`, have it in a branch that we then generate and pull in to master or some other strategy?

**Comment by gauntface** [comment]
I've closed the MDL stuff.

Do we want to move voice memos over to using this structure or is it low priority?

**Comment by addyosmani** [comment]
I'll file a new issue for voice-memos. I think prio wise for us, getting the blog post complete (#12) and maybe looking at file versioning would be ace next. If we've got cycles after, maybe then we can try porting voice-memos over in an uuuuber PR? :candy:

**Comment by addyosmani** [comment]
Filed https://github.com/GoogleChrome/application-shell/issues/37
