### ISSUE TITLE
Change the side nav top graphic

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/application-shell#25]
That's from Voice Memos :telephone_receiver:

**Comment by addyosmani** [comment]
I'll switch to one from the Material spec instead I think. Something like:

![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3Q0tDQ3Z1OHg5VHc/patterns_navdrawer_elevation1.png)
