### ISSUE TITLE
Setup deployment for GCloud or Heroku

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/application-shell#40]
We should make it easy to deploy the current setup to at least one of the above.

**Comment by jeffposnick** [comment]
FWIW, https://github.com/GoogleChrome/sw-precache/tree/app-shell-demo/app-shell-demo has a custom `Dockerfile` and `app.yaml` along with a `package.json`'s `scripts` section that should make both Heroku and [App Engine Node.js](https://cloud.google.com/nodejs/) happy.

Using the custom `Dockerfile` was necessarily as the default App Engine Node.js container is a bit buggy...

**Comment by addyosmani** [comment]
That's quite useful. I was just getting bogged down trying to get this setup with Node.js on GAE. Thanks @jeffposnick
