### ISSUE TITLE
Docs: How should you handle `<title>` for SEO?

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/application-shell#49]
Answer from Jake: 

> in the last I've populated `<title>` using a best guess from the url, then use js to set it properly later

Answer from me: 

> I think we've previously done not too different (default to site-wide `<title>`, later switch when can)

We verified this morning that presence of `<title>` in `<head>` followed by `<title>` later in `<body>` is not a workaround folks can rely on. That only works if there's no `<title>` defined in `<head>` previously. I think the idea of a best guess or default set using JS later is prolly a good answer.

**Comment by gauntface** [comment]
I was thinking a little about this and was considering moving app shell to have a more API like response rather than _just_ the HTML partial.

This way we could easily extract the HTML partial, Styles and extra info, like the page title, from a JSON response. Thoughts?

**Comment by addyosmani** [comment]
This should now be solved per 4cd96213292c579c2da5adad37baacdf7f6df53b if I understood correctly. Can has confirm/bug close if so? :)

**Comment by gauntface** [comment]
Yup yup.

Static render now pulls in a unique title for first render - this will be what the crawl bot should see. In app shell the title is altered by title from the json api.
