### ISSUE TITLE
Docs: Add clarity to the `<noscript>` part of the source

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/application-shell#50]
In reference to: https://github.com/GoogleChrome/application-shell/blob/9f56fd016ced3807b83b1f61a7ec03c97811ed1a/server/views/partials/async-css.handlebars#L28
- Folks wondering why they care about `noscript` in an architecture depending on `fetch` support
- Can we talk about server-rendering the first-request earlier on in the post? Let's figure out where this might make sense.
- Primary concern here is the SEO

**Comment by gauntface** [comment]
Responded to the two first bullet points, not sure what to comment on SEO - what was the concern?

**Comment by addyosmani** [comment]
Per chat, I think the concern was mostly that we didn't dive too deeply into how and if some of these decisions impact SEO. Imo, what we've added to the readme for this is definitely sufficient. Thanks dude.
