### ISSUE TITLE
Incognito tabs not maintaining breakpoints

### ISSUE THREAD

**Issue by julianeden** [GoogleChrome/application-shell#53]
Quite sorry if this is the wrong place for this, not sure where to report this as a Chrome dev tools bug.

For incognito tabs, breakpoints are not saved when you close and reopen them. Incognito mode is quite helpful for developers as it saves us having to clear cookies after each look at the page, but the fact that it removes break points anytime you close the tab is a major impediment.

This may be by design, in which case I would like to hear the argument for this "feature." Thank you!

**Comment by addyosmani** [comment]
If the bug is not specific to the application-shell project, could you file a new devtools bug at crbug.com and close this one please? :) It sounds like it's unrelated but if I've misread do let us know.
