### ISSUE TITLE
Server Rendering with asp.net core

### ISSUE THREAD

**Issue by manuelreina** [GoogleChrome/application-shell#74]
Hi, first of all, sorry because this is not an issue but a question. 

I have an angular 2 web application  with its application shell, push notifications, offline access, etc and everything works like a charm

Now I am trying to render it using angular universal and asp.net core but I don't know how to get the web app working offline.

I build my service worker with sw-precache and I tried with "dynamicUrlToDependencies", which works partially.

Could you please give me any guidance or resources?

Thank you.

**Comment by kamalakkanni** [comment]
service worker is not registered for me in asp.net core and angular universal which is working fine in angular and angularuniversal.How you used sw precache with this.Which folder files u cached
